version: '3'
services:
  mongo:
    image: mongo:3.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
      - data:/data/db
  prisma:
    image: prismagraphql/prisma:1.34
    env_file: ./server/config/dev.env
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo
  server:
    env_file: ./server/config/dev.env
    image: paulehair/ssdp-server
    restart: always
    working_dir: /app
    depends_on:
      - prisma
    volumes:
      - ./server:/app
    ports:
      - '9000:9000'
    entrypoint: ['yarn', 'start']

  client:
    env_file: ./client/src/.env
    image: paulehair/ssdp-client
    restart: always
    volumes:
      - ./client:/app
    ports:
      - '80:80'
    environment:
      SSDP_API_URL: http://localhost:9000
    stdin_open: true
    working_dir: /app

volumes:
  mongo: ~
  data: ~
