version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    environment:
      PRISMA_CONFIG: |
        port: {{ application_prisma_port }}
        databases:
          default:
            connector: mongo
            uri: {{ application_db_host }}
            port: {{ application_db_port }}
            user: foo
            password: mustbeeightchars
    ports:
      - "{{ application_prisma_port }}:4466"

  server:
    image: {{ application_server_image }}:latest
    env_file: ./prod.env
    restart: always
    working_dir: /app
    depends_on:
      - prisma
    ports:
      - "{{ application_server_port }}:9000"
    entrypoint: ['yarn', 'start']

  client:
    image: {{ application_client_image }}:latest
    env_file: ./prod.env #TODO
    restart: always
    ports:
      - "{{ application_client_port }}:3000"
    environment:
      SSDP_API_URL: "{{application_server_endpoint}}:{{ application_server_port }}"
    stdin_open: true
